repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/asottile/cheetah_lint
    rev: v0.5.0
    hooks:
    -   id: cheetah-flake
    -   id: cheetah-reorder-imports
